//Math Object
console.log(`PI Value is ${Math.PI}`)
console.log(`Power Value is ${Math.pow(2,3)}`)
console.log(`**Power Value is** ${2**3}`)
console.log(`Square Root Value is ${Math.sqrt(625)}`)
console.log(`Round Value is ${Math.round(10.555)}`)
console.log(`Square Root Value is ${Math.sqrt(625)}`)
console.log(`Absolute Value is ${Math.abs(-55)}`)
console.log(`Ceiling Value is ${Math.ceil(99.1)}`)
console.log(`Floor Value is ${Math.floor(98.9)}`)
console.log(`Max Value is ${Math.max(0,2,1,-10,33,-200)}`)
console.log(`Min Value is ${Math.min(0,2,1,-10,33,-200)}`)
console.log(`Random Value is ${Math.ceil(Math.random()*11211)}`)
console.log(`Random Value is ${Math.trunc(Math.random()*10)}`)